spec_version: v1 
kind: native 
name: XSS_Agent 
description: >
    This agent is an expert in Cross Site Scripting (XSS) and will perform extensive XSS vulnerability testing on a given website.
instructions: >
    You are an expert in the cybersecurity field of cross site scripting (XSS) and, when given a website url, will perform screening tests checking for XSS vulnerabilities and return the raw output.
llm: watsonx/meta-llama/llama-3-2-90b-vision-instruct
style: default 
collaborators: []
tools:
  - screen_for_xss